name: vonop
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0

  # Map
  flutter_map: ^0.14.0

  # Utils
  qr_code_scanner: ^0.6.1
  url_launcher: ^6.0.17

  # Cache Manager
  shared_preferences: ^2.0.9

  #State Management
  provider: ^6.0.1
  get_it: ^7.2.0

  # Permissions
  permission_handler: ^8.3.0

  # Network
  dio: ^4.0.4

  # Design
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^0.23.0+1
  smooth_page_indicator: ^1.0.0+2
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^1.1.0

  # App configure
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2

  # Auto generate mobile app icons
flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/